/* ChemicalSphere(TM) simulated decision layer - generated by generate_chemicalsphere_data.py */
window.CS_DATA = {
 "meta": {
  "generated": "2026-09-15",
  "months": 24,
  "baseline_months": 18,
  "batches": 5280,
  "pos": 1987,
  "shipments": 2719,
  "capa": 209,
  "plants": 6,
  "formulas": 12,
  "suppliers": 10,
  "periods": [
   "2024-10",
   "2024-11",
   "2024-12",
   "2025-01",
   "2025-02",
   "2025-03",
   "2025-04",
   "2025-05",
   "2025-06",
   "2025-07",
   "2025-08",
   "2025-09",
   "2025-10",
   "2025-11",
   "2025-12",
   "2026-01",
   "2026-02",
   "2026-03",
   "2026-04",
   "2026-05",
   "2026-06",
   "2026-07",
   "2026-08",
   "2026-09"
  ]
 },
 "kpi_defs": {
  "OEE": "mean(batch OEE) - availability x performance x quality, batch-weighted",
  "Yield %": "sum(actual_qty_t) / sum(planned_qty_t)",
  "Batch Success Rate": "1 - (failed batches / total batches)",
  "Throughput": "sum(actual_qty_t) per period",
  "Supplier OTIF": "sum(on_time_in_full) / count(PO lines)",
  "Lead Time Variance": "mean(actual_lead_days - planned_lead_days)",
  "Supplier Risk Score": "0-100 composite = 40%(1-OTIF) + 30%(norm lead variance) + 20%(quality reject rate) + 10%(geo risk)",
  "Formula Yield": "mean(yield_pct) by formula",
  "Product Margin %": "(revenue - total_cost) / revenue by product",
  "RM Cost Variance": "(actual rm_cost_per_t / baseline rm_cost_per_t) - 1",
  "CAPA Effectiveness": "1 - (recurring CAPA / total CAPA)",
  "Batch Rejection Rate": "failed batches / total batches",
  "Audit Compliance Score": "0-100 = 50%(CAPA closed on time) + 30%(CAPA effectiveness) + 20%(1 - rejection rate)",
  "Recall Readiness": "0-100 = % of sold volume with unbroken batch->shipment->customer genealogy",
  "Freight Cost per Tonne": "sum(freight_cost) / sum(qty_t)",
  "Logistics OTIF": "sum(on_time_in_full) / count(shipments)",
  "Logistics Risk Score": "0-100 composite = 55%(1-OTIF) + 45%(disruption rate)",
  "Inventory Turns": "annualised COGS / average inventory value",
  "Working Capital Days": "inventory value / (COGS/365)",
  "Cost per Batch": "sum(total_cost) / count(batches)",
  "Gross Margin %": "(revenue - total_cost) / revenue"
 },
 "thresholds": {
  "oee_floor": 0.78,
  "yield_floor": 0.88,
  "otif_floor": 0.9,
  "risk_ceiling": 28.0,
  "margin_floor": 0.12,
  "rm_var_ceiling": 0.14,
  "rejection_ceiling": 0.07,
  "capa_recur_ceiling": 0.34,
  "shelf_risk_ceiling": 0.3
 },
 "current": {
  "oee": 0.8349936363636363,
  "yield_pct": 0.9718489753411116,
  "batch_success": 0.956060606060606,
  "throughput": 27529.079999999998,
  "cost_per_batch": 53337.815227272724,
  "gross_margin_pct": 0.3097289451988306,
  "revenue": 50998745.79,
  "supplier_otif": 0.9471544715447154,
  "lead_time_var": 1.251219512195122,
  "logistics_otif": 0.9680232558139535,
  "freight_per_t": 103.69665744722938,
  "logistics_risk": 2.1511627906976716,
  "capa_effectiveness": 0.7058823529411764,
  "rejection_rate": 0.04393939393939394,
  "audit_score": 84.41532976827094,
  "recall_readiness": 96.06543299266718,
  "inventory_value": 85316564.50666666,
  "inventory_turns": 1.6504629905602552,
  "working_capital_days": 221.02888830979927,
  "shelf_life_risk_pct": 0.25925925925925924
 },
 "prior": {
  "oee": 0.8284583333333332,
  "yield_pct": 0.9562955043783528,
  "batch_success": 0.9454545454545454,
  "throughput": 26861.699999999997,
  "cost_per_batch": 51785.438242424236,
  "gross_margin_pct": 0.29191419750474523,
  "revenue": 48268711.39,
  "supplier_otif": 0.9473684210526315,
  "lead_time_var": 0.8125506072874495,
  "logistics_otif": 0.9396551724137931,
  "freight_per_t": 101.2765000870577,
  "logistics_risk": 4.999999999999997,
  "capa_effectiveness": 0.8695652173913043,
  "rejection_rate": 0.05454545454545454,
  "audit_score": 86.300395256917,
  "recall_readiness": 98.83413827510905,
  "inventory_value": 73063493.28333335,
  "inventory_turns": 1.87116096995031,
  "working_capital_days": 194.9591755377879,
  "shelf_life_risk_pct": 0.24074074074074073
 },
 "baseline": {
  "oee": 0.8085388888888888,
  "yield_pct": 0.9165249992433149,
  "batch_success": 0.9313131313131313,
  "throughput": 154735.55,
  "cost_per_batch": 51848.433911616165,
  "gross_margin_pct": 0.248046040516138,
  "revenue": 273048363.8,
  "supplier_otif": 0.9143239625167336,
  "lead_time_var": 0.48915662650602404,
  "logistics_otif": 0.9230389738529847,
  "freight_per_t": 100.69539362396577,
  "logistics_risk": 4.987666502220029,
  "capa_effectiveness": 0.7218934911242604,
  "rejection_rate": 0.06868686868686869,
  "audit_score": 77.85703185703186,
  "recall_readiness": 97.0507827021034,
  "inventory_value": 90144679.75277777,
  "inventory_turns": 1.5184464119464443,
  "working_capital_days": 240.2455543573483,
  "shelf_life_risk_pct": 0.2646604938271605
 },
 "live": {
  "oee": 0.8317259848484849,
  "yield_pct": 0.9641049329594193,
  "batch_success": 0.9507575757575758,
  "throughput": 54390.78,
  "cost_per_batch": 52561.626734848476,
  "gross_margin_pct": 0.3010665402238322,
  "revenue": 99267457.18,
  "supplier_otif": 0.947261663286004,
  "lead_time_var": 1.0314401622718055,
  "logistics_otif": 0.953757225433526,
  "freight_per_t": 102.47958105468786,
  "logistics_risk": 3.583815028901733,
  "capa_effectiveness": 0.8,
  "rejection_rate": 0.04924242424242424,
  "audit_score": 85.51515151515152,
  "recall_readiness": 97.42322573265143,
  "inventory_value": 79190028.89500001,
  "inventory_turns": 1.7522748320244816,
  "working_capital_days": 208.18652036366362,
  "shelf_life_risk_pct": 0.25
 },
 "trend": [
  {
   "period": "2024-10",
   "idx": 0,
   "cs_active": 0,
   "oee": 0.8178,
   "yield": 0.9173,
   "margin": 0.2653,
   "otif": 0.8831,
   "rejection": 0.0636,
   "inventory": 96024392.0,
   "throughput": 8942.0
  },
  {
   "period": "2024-11",
   "idx": 1,
   "cs_active": 0,
   "oee": 0.8112,
   "yield": 0.9157,
   "margin": 0.2644,
   "otif": 0.9205,
   "rejection": 0.0682,
   "inventory": 90530839.0,
   "throughput": 8736.0
  },
  {
   "period": "2024-12",
   "idx": 2,
   "cs_active": 0,
   "oee": 0.8163,
   "yield": 0.9183,
   "margin": 0.278,
   "otif": 0.9412,
   "rejection": 0.0409,
   "inventory": 86750128.0,
   "throughput": 8818.0
  },
  {
   "period": "2025-01",
   "idx": 3,
   "cs_active": 0,
   "oee": 0.804,
   "yield": 0.9126,
   "margin": 0.2234,
   "otif": 0.8736,
   "rejection": 0.0773,
   "inventory": 101995348.0,
   "throughput": 8069.0
  },
  {
   "period": "2025-02",
   "idx": 4,
   "cs_active": 0,
   "oee": 0.8072,
   "yield": 0.9161,
   "margin": 0.2197,
   "otif": 0.9375,
   "rejection": 0.0909,
   "inventory": 97452300.0,
   "throughput": 8812.0
  },
  {
   "period": "2025-03",
   "idx": 5,
   "cs_active": 0,
   "oee": 0.8042,
   "yield": 0.9121,
   "margin": 0.2603,
   "otif": 0.9556,
   "rejection": 0.0409,
   "inventory": 101138604.0,
   "throughput": 8573.0
  },
  {
   "period": "2025-04",
   "idx": 6,
   "cs_active": 0,
   "oee": 0.8108,
   "yield": 0.9152,
   "margin": 0.2384,
   "otif": 0.925,
   "rejection": 0.0636,
   "inventory": 89850128.0,
   "throughput": 8812.0
  },
  {
   "period": "2025-05",
   "idx": 7,
   "cs_active": 0,
   "oee": 0.8091,
   "yield": 0.9148,
   "margin": 0.2486,
   "otif": 0.9195,
   "rejection": 0.0591,
   "inventory": 73082840.0,
   "throughput": 8442.0
  },
  {
   "period": "2025-06",
   "idx": 8,
   "cs_active": 0,
   "oee": 0.8134,
   "yield": 0.9275,
   "margin": 0.2639,
   "otif": 0.8902,
   "rejection": 0.0727,
   "inventory": 97434315.0,
   "throughput": 8929.0
  },
  {
   "period": "2025-07",
   "idx": 9,
   "cs_active": 0,
   "oee": 0.8247,
   "yield": 0.9204,
   "margin": 0.2531,
   "otif": 0.9167,
   "rejection": 0.0955,
   "inventory": 76365773.0,
   "throughput": 8575.0
  },
  {
   "period": "2025-08",
   "idx": 10,
   "cs_active": 0,
   "oee": 0.7934,
   "yield": 0.9145,
   "margin": 0.2686,
   "otif": 0.9487,
   "rejection": 0.0636,
   "inventory": 89893647.0,
   "throughput": 8297.0
  },
  {
   "period": "2025-09",
   "idx": 11,
   "cs_active": 0,
   "oee": 0.8004,
   "yield": 0.912,
   "margin": 0.2206,
   "otif": 0.8987,
   "rejection": 0.1045,
   "inventory": 81291529.0,
   "throughput": 8875.0
  },
  {
   "period": "2025-10",
   "idx": 12,
   "cs_active": 0,
   "oee": 0.8051,
   "yield": 0.9171,
   "margin": 0.1777,
   "otif": 0.9036,
   "rejection": 0.1318,
   "inventory": 87476972.0,
   "throughput": 8377.0
  },
  {
   "period": "2025-11",
   "idx": 13,
   "cs_active": 0,
   "oee": 0.8153,
   "yield": 0.9176,
   "margin": 0.222,
   "otif": 0.9368,
   "rejection": 0.0818,
   "inventory": 82437552.0,
   "throughput": 8554.0
  },
  {
   "period": "2025-12",
   "idx": 14,
   "cs_active": 0,
   "oee": 0.8119,
   "yield": 0.9161,
   "margin": 0.2627,
   "otif": 0.9146,
   "rejection": 0.05,
   "inventory": 94930645.0,
   "throughput": 8002.0
  },
  {
   "period": "2026-01",
   "idx": 15,
   "cs_active": 0,
   "oee": 0.8092,
   "yield": 0.9161,
   "margin": 0.2706,
   "otif": 0.9186,
   "rejection": 0.0364,
   "inventory": 80141071.0,
   "throughput": 8516.0
  },
  {
   "period": "2026-02",
   "idx": 16,
   "cs_active": 0,
   "oee": 0.8009,
   "yield": 0.9193,
   "margin": 0.2536,
   "otif": 0.9012,
   "rejection": 0.0545,
   "inventory": 95633334.0,
   "throughput": 9201.0
  },
  {
   "period": "2026-03",
   "idx": 17,
   "cs_active": 0,
   "oee": 0.799,
   "yield": 0.9142,
   "margin": 0.2623,
   "otif": 0.8659,
   "rejection": 0.0409,
   "inventory": 100174820.0,
   "throughput": 8203.0
  },
  {
   "period": "2026-04",
   "idx": 18,
   "cs_active": 1,
   "oee": 0.8206,
   "yield": 0.9354,
   "margin": 0.2711,
   "otif": 0.9452,
   "rejection": 0.0636,
   "inventory": 78093487.0,
   "throughput": 8148.0
  },
  {
   "period": "2026-05",
   "idx": 19,
   "cs_active": 1,
   "oee": 0.831,
   "yield": 0.9584,
   "margin": 0.2926,
   "otif": 0.9535,
   "rejection": 0.05,
   "inventory": 71956075.0,
   "throughput": 9222.0
  },
  {
   "period": "2026-06",
   "idx": 20,
   "cs_active": 1,
   "oee": 0.8337,
   "yield": 0.9729,
   "margin": 0.3102,
   "otif": 0.9432,
   "rejection": 0.05,
   "inventory": 69140918.0,
   "throughput": 9492.0
  },
  {
   "period": "2026-07",
   "idx": 21,
   "cs_active": 1,
   "oee": 0.8377,
   "yield": 0.9714,
   "margin": 0.3143,
   "otif": 0.908,
   "rejection": 0.0409,
   "inventory": 84293820.0,
   "throughput": 8854.0
  },
  {
   "period": "2026-08",
   "idx": 22,
   "cs_active": 1,
   "oee": 0.8331,
   "yield": 0.9698,
   "margin": 0.3165,
   "otif": 0.9753,
   "rejection": 0.0273,
   "inventory": 87958629.0,
   "throughput": 9066.0
  },
  {
   "period": "2026-09",
   "idx": 23,
   "cs_active": 1,
   "oee": 0.8342,
   "yield": 0.9742,
   "margin": 0.2982,
   "otif": 0.9615,
   "rejection": 0.0636,
   "inventory": 83697245.0,
   "throughput": 9610.0
  }
 ],
 "suppliers": [
  {
   "supplier_id": "SUP-07",
   "otif": 0.7955,
   "ltv": 13.0977,
   "rej": 0.0682,
   "value": 23850168.11,
   "supplier_name": "Caspian Intermed",
   "geo_risk": "High",
   "region": "EMEA",
   "risk_score": 34.3
  },
  {
   "supplier_id": "SUP-05",
   "otif": 0.902,
   "ltv": -0.4902,
   "rej": 0.0392,
   "value": 16195223.65,
   "supplier_name": "Andes Minerals",
   "geo_risk": "Medium",
   "region": "LATAM",
   "risk_score": 9.7
  },
  {
   "supplier_id": "SUP-10",
   "otif": 0.9318,
   "ltv": 0.6114,
   "rej": 0.0,
   "value": 6523529.03,
   "supplier_name": "Atlas Pigments",
   "geo_risk": "Medium",
   "region": "EMEA",
   "risk_score": 8.5
  },
  {
   "supplier_id": "SUP-06",
   "otif": 0.92,
   "ltv": -0.258,
   "rej": 0.0,
   "value": 12237884.6,
   "supplier_name": "Pacific Catalysts",
   "geo_risk": "Medium",
   "region": "APAC",
   "risk_score": 8.2
  },
  {
   "supplier_id": "SUP-03",
   "otif": 0.9787,
   "ltv": 0.4383,
   "rej": 0.0213,
   "value": 19516485.9,
   "supplier_name": "Shandong Additives",
   "geo_risk": "Medium",
   "region": "APAC",
   "risk_score": 6.8
  },
  {
   "supplier_id": "SUP-02",
   "otif": 0.9796,
   "ltv": 0.649,
   "rej": 0.0408,
   "value": 15964591.79,
   "supplier_name": "Gulf Feedstocks",
   "geo_risk": "Low",
   "region": "AMER",
   "risk_score": 3.9
  },
  {
   "supplier_id": "SUP-01",
   "otif": 0.9818,
   "ltv": -0.7764,
   "rej": 0.0727,
   "value": 25086042.32,
   "supplier_name": "Nordic Petrochem",
   "geo_risk": "Low",
   "region": "EMEA",
   "risk_score": 3.7
  },
  {
   "supplier_id": "SUP-08",
   "otif": 0.9608,
   "ltv": 0.051,
   "rej": 0.0,
   "value": 15003594.52,
   "supplier_name": "Bharat Speciality",
   "geo_risk": "Low",
   "region": "APAC",
   "risk_score": 3.1
  },
  {
   "supplier_id": "SUP-09",
   "otif": 1.0,
   "ltv": -0.9737,
   "rej": 0.0175,
   "value": 30259958.79,
   "supplier_name": "Lone Star Polymers",
   "geo_risk": "Low",
   "region": "AMER",
   "risk_score": 1.9
  },
  {
   "supplier_id": "SUP-04",
   "otif": 1.0,
   "ltv": -0.3022,
   "rej": 0.0,
   "value": 17481380.7,
   "supplier_name": "Rhine Solvents",
   "geo_risk": "Low",
   "region": "EMEA",
   "risk_score": 1.5
  }
 ],
 "plants": [
  {
   "plant_id": "PLT-03",
   "oee": 0.6295,
   "yld": 0.9274,
   "rej": 0.1038,
   "tput": 6318.64,
   "margin": 2059961.11,
   "cost": 8730741.42,
   "rev": 10790702.53,
   "plant_name": "Jurong Island",
   "region": "APAC",
   "margin_pct": 0.1909
  },
  {
   "plant_id": "PLT-05",
   "oee": 0.822,
   "yld": 0.9594,
   "rej": 0.0269,
   "tput": 6918.73,
   "margin": 4085594.17,
   "cost": 9077688.19,
   "rev": 13163282.36,
   "plant_name": "Camacari Unit",
   "region": "LATAM",
   "margin_pct": 0.3104
  },
  {
   "plant_id": "PLT-06",
   "oee": 0.8531,
   "yld": 0.9566,
   "rej": 0.0558,
   "tput": 9679.35,
   "margin": 5409621.15,
   "cost": 12741681.46,
   "rev": 18151302.61,
   "plant_name": "Dahej Plant",
   "region": "APAC",
   "margin_pct": 0.298
  },
  {
   "plant_id": "PLT-02",
   "oee": 0.8646,
   "yld": 0.9622,
   "rej": 0.0431,
   "tput": 12641.77,
   "margin": 6901954.95,
   "cost": 15230763.86,
   "rev": 22132718.81,
   "plant_name": "Houston Complex",
   "region": "AMER",
   "margin_pct": 0.3118
  },
  {
   "plant_id": "PLT-01",
   "oee": 0.882,
   "yld": 0.9595,
   "rej": 0.0409,
   "tput": 9073.19,
   "margin": 5388591.48,
   "cost": 11382704.08,
   "rev": 16771295.56,
   "plant_name": "Rotterdam Works",
   "region": "EMEA",
   "margin_pct": 0.3213
  },
  {
   "plant_id": "PLT-04",
   "oee": 0.9035,
   "yld": 0.9598,
   "rej": 0.0332,
   "tput": 9759.1,
   "margin": 6040387.03,
   "cost": 12217768.28,
   "rev": 18258155.31,
   "plant_name": "Ludwigshafen Site",
   "region": "EMEA",
   "margin_pct": 0.3308
  }
 ],
 "formulas": [
  {
   "formula_id": "FRM-09",
   "product_family": "Specialty",
   "yld": 0.8752,
   "rmc": 1639.091,
   "rev": 7012367.41,
   "cost": 7419187.16,
   "rej": 0.0962,
   "vol": 2958.26,
   "formula_name": "SpecialtyBlend Z",
   "margin_pct": -0.058,
   "rm_var": 0.0238
  },
  {
   "formula_id": "FRM-10",
   "product_family": "Agrochem",
   "yld": 0.9633,
   "rmc": 586.9032,
   "rev": 6956143.01,
   "cost": 5061212.63,
   "rej": 0.0472,
   "vol": 6003.1,
   "formula_name": "AgriNute K25",
   "margin_pct": 0.2724,
   "rm_var": 0.0229
  },
  {
   "formula_id": "FRM-04",
   "product_family": "Agrochem",
   "yld": 0.9565,
   "rmc": 554.5496,
   "rev": 8053347.59,
   "cost": 5744224.57,
   "rej": 0.0354,
   "vol": 7151.73,
   "formula_name": "AgriNute N40",
   "margin_pct": 0.2867,
   "rm_var": 0.0255
  },
  {
   "formula_id": "FRM-05",
   "product_family": "Coatings",
   "yld": 0.9385,
   "rmc": 1342.3518,
   "rev": 7807851.33,
   "cost": 5478985.55,
   "rej": 0.0594,
   "vol": 2784.6,
   "formula_name": "CoatPrime TiO",
   "margin_pct": 0.2983,
   "rm_var": 0.0213
  },
  {
   "formula_id": "FRM-08",
   "product_family": "Surfactants",
   "yld": 0.9687,
   "rmc": 1063.0414,
   "rev": 9451932.68,
   "cost": 6456192.17,
   "rej": 0.0328,
   "vol": 4272.39,
   "formula_name": "SurfActa 900",
   "margin_pct": 0.3169,
   "rm_var": 0.0231
  },
  {
   "formula_id": "FRM-11",
   "product_family": "Polymers",
   "yld": 0.9721,
   "rmc": 741.532,
   "rev": 8191237.77,
   "cost": 5576240.97,
   "rej": 0.0642,
   "vol": 5289.99,
   "formula_name": "PolyFlex LD",
   "margin_pct": 0.3192,
   "rm_var": 0.0256
  },
  {
   "formula_id": "FRM-02",
   "product_family": "Polymers",
   "yld": 0.9652,
   "rmc": 904.5391,
   "rev": 8286745.03,
   "cost": 5520134.98,
   "rej": 0.0187,
   "vol": 4268.55,
   "formula_name": "PolyBond 400HD",
   "margin_pct": 0.3339,
   "rm_var": 0.023
  },
  {
   "formula_id": "FRM-06",
   "product_family": "Coatings",
   "yld": 0.9447,
   "rmc": 1456.3768,
   "rev": 9225475.39,
   "cost": 6127176.77,
   "rej": 0.0427,
   "vol": 2876.86,
   "formula_name": "EpoxSeal 7",
   "margin_pct": 0.3358,
   "rm_var": 0.0265
  },
  {
   "formula_id": "FRM-07",
   "product_family": "Catalysts",
   "yld": 0.9183,
   "rmc": 15188.0521,
   "rev": 8188308.17,
   "cost": 5425208.27,
   "rej": 0.0531,
   "vol": 237.16,
   "formula_name": "CatalystPro Pt",
   "margin_pct": 0.3374,
   "rm_var": 0.0232
  },
  {
   "formula_id": "FRM-01",
   "product_family": "Polymers",
   "yld": 0.9777,
   "rmc": 771.0542,
   "rev": 8395932.58,
   "cost": 5477814.36,
   "rej": 0.0561,
   "vol": 5045.32,
   "formula_name": "PolyBond 200",
   "margin_pct": 0.3476,
   "rm_var": 0.0233
  },
  {
   "formula_id": "FRM-12",
   "product_family": "Solvents",
   "yld": 0.9851,
   "rmc": 621.2254,
   "rev": 8019971.88,
   "cost": 5079547.93,
   "rej": 0.0377,
   "vol": 5835.18,
   "formula_name": "PureSolve 99",
   "margin_pct": 0.3666,
   "rm_var": 0.023
  },
  {
   "formula_id": "FRM-03",
   "product_family": "Solvents",
   "yld": 0.9901,
   "rmc": 563.7554,
   "rev": 9678144.34,
   "cost": 6015421.93,
   "rej": 0.0522,
   "vol": 7667.64,
   "formula_name": "SolvClear X",
   "margin_pct": 0.3785,
   "rm_var": 0.0263
  }
 ],
 "inventory": [
  {
   "plant_id": "PLT-02",
   "value": 18739026.97,
   "risk": 0.25,
   "age": 99.6833,
   "plant_name": "Houston Complex"
  },
  {
   "plant_id": "PLT-05",
   "value": 18196234.81,
   "risk": 0.4167,
   "age": 137.125,
   "plant_name": "Camacari Unit"
  },
  {
   "plant_id": "PLT-01",
   "value": 14270827.52,
   "risk": 0.1667,
   "age": 91.3667,
   "plant_name": "Rotterdam Works"
  },
  {
   "plant_id": "PLT-03",
   "value": 12017215.23,
   "risk": 0.1667,
   "age": 80.375,
   "plant_name": "Jurong Island"
  },
  {
   "plant_id": "PLT-06",
   "value": 10311600.54,
   "risk": 0.1667,
   "age": 80.9083,
   "plant_name": "Dahej Plant"
  },
  {
   "plant_id": "PLT-04",
   "value": 10162339.6,
   "risk": 0.1667,
   "age": 85.525,
   "plant_name": "Ludwigshafen Site"
  }
 ],
 "agents": [
  {
   "agent": "Production Optimization Agent",
   "severity": "Critical",
   "entity": "Jurong Island (PLT-03)",
   "signal": "OEE 63.0% vs floor 78%",
   "finding": "Sustained OEE shortfall with yield at 92.7% and rejection at 10.4%.",
   "action": "Rebalance ~15% of PLT-03 volume to PLT-04 / PLT-02; trigger asset reliability review on the constraint unit.",
   "impact": "+951 t recoverable throughput per quarter",
   "domain": "Manufacturing"
  },
  {
   "agent": "Formula Intelligence Agent",
   "severity": "Critical",
   "entity": "SpecialtyBlend Z (FRM-09)",
   "signal": "Margin -5.8% | RM cost variance +2.4%",
   "finding": "Recipe economics deteriorating; yield 87.5% against a Specialty portfolio norm.",
   "action": "Run substitution scenario on the two highest-cost ingredients; re-qualify alternate grade and reprice contract tier.",
   "impact": "$1,248,304 annualised margin recovery at current volume",
   "domain": "Formula"
  },
  {
   "agent": "Compliance Agent",
   "severity": "Critical",
   "entity": "Agrochem product line",
   "signal": "CAPA recurrence 42.9% | 7 open investigations",
   "finding": "Dominant root cause: Process parameter drift. Recurrence indicates ineffective corrective action.",
   "action": "Escalate to a line-level CAPA effectiveness review; pre-stage recall simulation and refresh GHS/REACH dossiers for affected batches.",
   "impact": "7 batches brought to audit-ready traceability",
   "domain": "Quality"
  },
  {
   "agent": "Compliance Agent",
   "severity": "Critical",
   "entity": "Catalysts product line",
   "signal": "CAPA recurrence 66.7% | 3 open investigations",
   "finding": "Dominant root cause: Operator deviation. Recurrence indicates ineffective corrective action.",
   "action": "Escalate to a line-level CAPA effectiveness review; pre-stage recall simulation and refresh GHS/REACH dossiers for affected batches.",
   "impact": "3 batches brought to audit-ready traceability",
   "domain": "Quality"
  },
  {
   "agent": "Supplier Risk Agent",
   "severity": "High",
   "entity": "Caspian Intermed (SUP-07)",
   "signal": "Risk score 34/100 | OTIF 79.5% | lead variance +13.1 d",
   "finding": "High geopolitical exposure compounding delivery deterioration across EMEA.",
   "action": "Dual-source top 3 materials; shift 35% of spend to a qualified alternate and raise safety stock one cycle.",
   "impact": "$8,347,559 spend de-risked; exposure window cut by ~13 days",
   "domain": "Supply Chain"
  },
  {
   "agent": "Inventory Intelligence Agent",
   "severity": "High",
   "entity": "Camacari Unit (PLT-05)",
   "signal": "Shelf-life risk 41.7% | avg age 137 d | $18,196,235 held",
   "finding": "Slow-moving stock ageing past the safe-resale window at this node.",
   "action": "Reposition to nearest demand region, convert to lower-grade blend, or throttle replenishment for two cycles.",
   "impact": "$2,547,473 working capital released",
   "domain": "Financial"
  },
  {
   "agent": "CFO Agent",
   "severity": "Medium",
   "entity": "Enterprise portfolio",
   "signal": "Gross margin 31.0% | inventory turns 1.7 | WC 221 d",
   "finding": "Commodity index shock is transmitting into cost per batch faster than price realisation.",
   "action": "Rationalise the bottom-quartile formula set, pull forward inventory reduction on the two highest-value nodes, and reprice indexed contracts.",
   "impact": "$10,237,988 working capital + margin protection",
   "domain": "Financial"
  }
 ],
 "outcomes": [
  {
   "label": "Inventory carrying value",
   "target": "10-15% reduction",
   "unit": "$",
   "baseline": 90144679.75277777,
   "live": 79190028.89500001,
   "delta_pct": 0.12152298824313253
  },
  {
   "label": "Plant yield",
   "target": "5-10% improvement",
   "unit": "%",
   "baseline": 0.9165249992433149,
   "live": 0.9641049329594193,
   "delta_pct": 0.05191340525941635
  },
  {
   "label": "Supplier OTIF",
   "target": "20-30% faster decisions",
   "unit": "%",
   "baseline": 0.9143239625167336,
   "live": 0.947261663286004,
   "delta_pct": 0.03602410318396043
  },
  {
   "label": "Batch rejection rate",
   "target": "Reduced batch failures",
   "unit": "%",
   "baseline": 0.06868686868686869,
   "live": 0.04924242424242424,
   "delta_pct": 0.28308823529411764
  },
  {
   "label": "Audit compliance score",
   "target": "Improved readiness",
   "unit": "pts",
   "baseline": 77.85703185703186,
   "live": 85.51515151515152,
   "delta_pct": 0.09836131015348996
  },
  {
   "label": "Working capital days",
   "target": "Better WC performance",
   "unit": "days",
   "baseline": 240.2455543573483,
   "live": 208.18652036366362,
   "delta_pct": 0.13344277724281692
  },
  {
   "label": "Gross margin",
   "target": "Margin protection",
   "unit": "%",
   "baseline": 0.248046040516138,
   "live": 0.3010665402238322,
   "delta_pct": 0.2137526549400602
  },
  {
   "label": "Inventory turns",
   "target": "Higher velocity",
   "unit": "x",
   "baseline": 1.5184464119464443,
   "live": 1.7522748320244816,
   "delta_pct": 0.1539918815958087
  }
 ],
 "genealogy": {
  "batch_id": "BAT-000118",
  "plant": "Houston Complex",
  "formula": "SpecialtyBlend Z",
  "materials": [
   {
    "material_name": "Propylene",
    "proportion": 0.3971,
    "hazard_class": "Flammable"
   },
   {
    "material_name": "Butadiene",
    "proportion": 0.1042,
    "hazard_class": "Flammable"
   },
   {
    "material_name": "Epoxy Resin Base",
    "proportion": 0.2023,
    "hazard_class": "Irritant"
   },
   {
    "material_name": "Ethylene",
    "proportion": 0.1429,
    "hazard_class": "Flammable"
   },
   {
    "material_name": "Antioxidant AO-7",
    "proportion": 0.1535,
    "hazard_class": "Irritant"
   }
  ],
  "suppliers": [
   {
    "supplier_id": "SUP-06",
    "supplier_name": "Pacific Catalysts",
    "geo_risk": "Medium"
   },
   {
    "supplier_id": "SUP-05",
    "supplier_name": "Andes Minerals",
    "geo_risk": "Medium"
   },
   {
    "supplier_id": "SUP-02",
    "supplier_name": "Gulf Feedstocks",
    "geo_risk": "Low"
   }
  ],
  "shipments": [],
  "customers": [
   {
    "customer_id": "CUS-06",
    "customer_name": "Detroit AutoParts",
    "region": "AMER"
   },
   {
    "customer_id": "CUS-02",
    "customer_name": "Midwest AgriCorp",
    "region": "AMER"
   },
   {
    "customer_id": "CUS-08",
    "customer_name": "Nordic Paints AS",
    "region": "EMEA"
   }
  ]
 }
};
